### ISSUE TITLE
weird issue maybe you know what were doing wrong?

### ISSUE THREAD

**Issue by SquirrelAssassin** [jantman/misc-scripts#4]

**Comment by SquirrelAssassin** [comment]
[vagrant@master ~]$ ./aws_subnet_available_ips.py subnet-2af5bd16
[INFO credentials.py:1031 -                 load() ] Found credentials in shared credentials file: ~/.aws/credentials
[INFO aws_subnet_available_ips.py:46 -             __init__() ] Connected to AWS API
[INFO aws_subnet_available_ips.py:170 - _find_classic_subnet() ] Querying for subnet
[INFO connectionpool.py:735 -            _new_conn() ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
Traceback (most recent call last):
  File "./aws_subnet_available_ips.py", line 200, in <module>
    print(finder.show_subnet_usage(args.SUBNET_ID_OR_BLOCK))
  File "./aws_subnet_available_ips.py", line 52, in show_subnet_usage
    subnet['SubnetId'],
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by jantman** [comment]
This is a really old script and could benefit from a bit of additional error handling, but at first glance it looks like ``subnet-2af5bd16`` doesn't exist as a subnet in the us-east-1 region of the account that you're connected to...

**Comment by SquirrelAssassin** [comment]
Actually think its a permission issue this acount can't just list all subnets either.  Will update later today.

**Comment by jantman** [comment]
Ok. Please reopen if you believe it's an issue with this code.
